export = {
    SET_CURRENT_MUSIC: 'SET_CURRENT_MUSIC',
    REMOVE_BLOCKED: 'REMOVE_BLOCKED',
    SET_SETTINGS: 'SET_SETTINGS',
    BLOCK_ADS_ON_24H: 'BLOCK_ADS_ON_24H',
    SET_CUSTOM_SONGS_LIST: 'SET_CUSTOM_SONGS_LIST',
    SET_COUNT_OF_REWARDS: 'SET_COUNT_OF_REWARDS'
} 